"""empty message

Revision ID: 01b71e2e3109
Revises: 9a3ad803efee
Create Date: 2025-01-25 19:34:35.036510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b71e2e3109'
down_revision = '9a3ad803efee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_activities', schema=None) as batch_op:
        batch_op.alter_column('distance_number',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('distance_units',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_activities', schema=None) as batch_op:
        batch_op.alter_column('distance_units',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('distance_number',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
