"""tasks table

Revision ID: 049b58bf4fb7
Revises: 076e4a2e8739
Create Date: 2024-11-17 16:22:20.341350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049b58bf4fb7'
down_revision = '076e4a2e8739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))
        batch_op.drop_column('deletged')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deletged', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
