"""empty message

Revision ID: 3e7afd42c1c4
Revises: a19894198300
Create Date: 2024-12-18 15:35:03.550982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7afd42c1c4'
down_revision = 'a19894198300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_creator', sa.String(length=100), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_column('content_creator')

    # ### end Alembic commands ###
