"""empty message

Revision ID: 438e84b764e0
Revises: 381da283d416
Create Date: 2025-01-29 07:02:14.349653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438e84b764e0'
down_revision = '381da283d416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semi_companies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semi_companies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
