"""empty message

Revision ID: 469749a94cee
Revises: bf7b6b399cf8
Create Date: 2025-01-01 20:31:59.273012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469749a94cee'
down_revision = 'bf7b6b399cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_entries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_weight_entries_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    with op.batch_alter_table('weight_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_weight_entries_timestamp'))

    op.drop_table('weight_entries')
    # ### end Alembic commands ###
