"""add deleted column

Revision ID: 491d4288a890
Revises: 1a25a77935e2
Create Date: 2024-11-17 16:26:23.122727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491d4288a890'
down_revision = '1a25a77935e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
