"""updates to post

Revision ID: 71dec90f2402
Revises: 70204df7b64e
Create Date: 2024-12-01 21:58:18.758616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dec90f2402'
down_revision = '70204df7b64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.DateTime(), nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('title')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
