"""empty message

Revision ID: 9a3ad803efee
Revises: b8b7490a7100
Create Date: 2025-01-25 19:31:16.140715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3ad803efee'
down_revision = 'b8b7490a7100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_activities', schema=None) as batch_op:
        batch_op.alter_column('distance_number',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('distance_units',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_activities', schema=None) as batch_op:
        batch_op.alter_column('distance_units',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('distance_number',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
