"""empty message

Revision ID: bf013615a0ee
Revises: 469749a94cee
Create Date: 2025-01-02 12:56:34.592020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf013615a0ee'
down_revision = '469749a94cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column("timestamp", new_column_name="timestamp_entry")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_activities', schema=None) as batch_op:
        batch_op.alter_column("timestamp_entry", new_column_name="timestamp")
        batch_op.drop_column('date')

    # ### end Alembic commands ###
